blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://forum.cohabitat.io/
    about: 'For ideas or feature requests'
  - name: Support Questions & Other
    url: https://forum.cohabitat.io/
    about: 'If you have a question or need help'
